### ISSUE TITLE
Memory usage 84G

### ISSUE THREAD

**Issue by lk479o000** [dogechain-lab/dogechain#179]
I'm run dogechain node, Synchronized to the latest block.
The memory utilization rate has gradually increased to 84G.
This is far from the official recommendation. How can I limit the memory usage?

vCPUs >= 4
Memory: at least 8GB
Disk space
at least 200GB for the data directory ( recommend SSD )
data disk mount to /data

CONTAINER ID   NAME          CPU %     MEM USAGE / LIMIT     MEM %     NET I/O           BLOCK I/O         PIDS
d20ef9699492   dogechain         0.72%     83.99GiB / 249.2GiB   33.71%    17.6GB / 19.58GB   1.85GB / 10.16TB   39

**Comment by 0xcb9ff9** [comment]
maybe because of this #178 #176
if you use `docker compose` can configure `mem_limit`, limit memory

`docker-compose.yml` like this
```yaml
version: "2"

services:
  dogechain:
    image: "dogechainlab/dogechain:1.1.3"
    container_name: dogechain
    restart: always
    # limit memory to 8GB
    mem_limit: 8g
    ports:
      # p2p port
      - "1478:1478"
      # http rpc port
      - "8545:8545"
      # grpc port 
      - "9632:9632"
    volumes:
      # if data directory exists in host /data directory
      - /data:/data
      # genesis.json file
      - ./genesis.json:/genesis.json
    ulimits:
      nofile:
        soft: 65536
        hard: 65536
    command:
      - "server"
      - "--data-dir=/data/dogechain"
      - "--chain=/genesis.json"
      - "--seal"
      - "--max-slots=4096"
      - "--grpc=0.0.0.0:9632"
      - "--libp2p=0.0.0.0:1478"
      - "--jsonrpc=0.0.0.0:8545"
      - "--max-inbound-peers=32"
      - "--max-outbound-peers=32"
      # replace with your public ip
      # you can use haproxy proxy the port (tcp)
      - "--nat=[YOUR_PUBLIC_IP]:1478"
```
